FROM ubuntu:devel


RUN apt update &&\
apt -y install libavfilter-dev\
    libavdevice-dev libavcodec-dev libavformat-dev\
    libavutil-dev libswresample-dev\
    libswscale-dev make cmake pkg-config g++


